# Complete the ELK stack. Run this playbook after running the core playbook
# (terraform.sample.yml)

# CHECK SECURITY - when customizing you should leave this in. If you take it out
# and forget to specify security.yml, security could be turned off on components
# in your cluster!
- include: "{{ playbook_dir }}/../playbooks/check-requirements.yml"

- hosts: role=control
  roles:
    - elk

- hosts: all
  vars:
    heka_output: elasticsearch
    heka_elasticsearch_output:
      message_matcher: "TRUE"
      server: "http://elasticsearch.service.consul:4000"
      flush_interval: 30
  roles:
    - heka
